# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: feigeCode.Navop
PackageVersion: 0.18.6
InstallerType: burn
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-09-21
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/feigeCode/navop/releases/download/v0.18.6/navop-0.18.6-win32.exe
  InstallerSha256: F77E9B748C2DCC231FF0B2C788352B390DC9557517E4C604728AE5CED8120B1E
  AppsAndFeaturesEntries:
  - ProductCode: '{5004EDE1-BE46-425D-9A58-3561DA8F43FC}'
    UpgradeCode: '{38BD57EC-1F89-5BD2-AF7B-E3115AF8F8B4}'
    InstallerType: burn
- Architecture: x64
  InstallerUrl: https://github.com/feigeCode/navop/releases/download/v0.18.6/navop-0.18.6-windows-x64.exe
  InstallerSha256: 16F6369290996A2A6480DC17FD1DC1CECFCBA35E59489C3279A2E0CF0E84EA3D
  AppsAndFeaturesEntries:
  - ProductCode: '{A6194361-44CF-4BA5-8BB3-DC43DA320B27}'
    UpgradeCode: '{38BD57EC-1F89-5BD2-AF7B-E3115AF8F8B4}'
    InstallerType: burn
ManifestType: installer
ManifestVersion: 1.12.0
